all: spring_intro spring_webdev mybatis_intro mybatis_advanced
 
spring_intro:
	mkdir spring-intro/output -p
	cd spring-intro/output; pdflatex ../intro.tex

spring_webdev:
	mkdir spring-webdev/output -p
	cd spring-webdev/output; pdflatex ../webdev.tex

mybatis_intro:
	mkdir mybatis-intro/output -p
	cd mybatis-intro/output; pdflatex ../intro.tex

mybatis_advanced:
	mkdir mybatis-advanced/output -p
	cd mybatis-advanced/output; pdflatex ../advanced.tex

clean:
	rm */output -rf


